geofence_monitor:
  ros__parameters:
    fence_csv: "/root/stack_can_ws/data/fence.csv"
    gps_topic: "/fix_center"          # 你用于控制的GNSS中心点
    warn_margin_m: 2.0                # 距离边界<5m进入WARN
    check_period_s: 0.2
    abort_on_outside: true

traj_waypoint_follower:
  ros__parameters:
    # 路径与传感器
    path_csv: "/root/stack_can_ws/data/points.csv"
    gps_topic: "/fix_center"
    imu_topic: "/imu/data"

    use_rtk_heading: true
    rtk_heading_topic: "/vehicle_heading_deg"
    yaw_offset_deg: 0.0

    # 几何控制
    lookahead_dist: 1.5
    advance_when_close: 2.0
    t_advance_min: 0.8

    # 任务点
    use_csv_heading: true
    align_heading_only_at_task_points: true
    heading_align_dist: 1.0
    wp_reached_dist: 1.0
    wp_heading_tol_deg: 10.0
    stop_turn_tol_deg: 10.0
    wait_for_task_done: true
    task_done_topic: "/task_done"

    # 坐标系
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    traj_path_len: 2000

    # CAN
    enable_can: true
    can_interface: "can0"
    can_extended: true
    can_id_status: 0x18FED188
    link_remote_to_abort: true

    # DR（可按需求开启/关闭）
    dead_reckon: false
    dr_alpha: 0.3
    dr_use_gps_speed: true

    # VCU 离散控制
    vcu_speed_fast_kmh: 8.0
    vcu_speed_slow_kmh: 4.0
    vcu_speed_stop_kmh: 0.0

    # 角度档 & 阈值（与你 stack 硬件保持一致）
    vcu_angle_move_limit_deg: 20.0
    vcu_turn_small_cmd_deg: 10.0
    vcu_turn_large_cmd_deg: 20.0
    vcu_turn_small_thresh_deg: 5.0
    vcu_turn_large_thresh_deg: 10.0

    # SPIN 进入/退出条件
    vcu_angle_spin_enter_deg: 20.0
    vcu_angle_spin_exit_deg: 18.0
    vcu_angle_spin_cmd_deg: 20.0
    spin_pre_stop_time_s: 0.7   # 从低速/高速进入原地旋转前，保持 0速0角 的时间（秒）

    # 拐角识别
    strict_corner_mode: true
    corner_start_dist: 1.0
    corner_sharp_deg_strict: 45.0
    strict_hold_deg: 2.0

    # 误差阈值
    emergency_spin_hdg_deg: 35.0   # 比你原来 55° 更容易触发紧急 SPIN
    hdg_deadband_deg: 1.0
    cte_deadband_m: 0.1
    sign_hysteresis_deg: 1.0

stack_can_executor:
  ros__parameters:
    enable_can: true
    can_interface: "can0"
    can_extended: true
    can_id_status: 0x18FED188

    vcu_speed_raw_offset_kmh: -50.0
    vcu_speed_raw_res_kmh_per_lsb: 0.5
